### ISSUE TITLE
NPM version 0.1.14 is using broken package.json

### ISSUE THREAD

**Issue by vbontempi** [ibm-cds-labs/bluemix-helper-config#7]
The version 0.1.14 currently available on NPM is using the broken version of the module package.json using @ in the notation for the async dependency.

**Comment by ptitzler** [comment]
@vbontempi.  We've re-published the module. Version 0.1.15 should now work!

**Comment by lornajane** [comment]
The version 0.15 and 0.16 versions seem to be working OK for me, so I'll mark this as closed.  Let us know if you see any other issues!
